version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blog
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t public
    environment:
      APP_KEY: ${APP_KEY}
    volumes:
      - ./:/var/www
    networks:
      - blog

  db:
    image: mysql
    container_name: blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - blog

networks:
  blog:
    driver: bridge
